apiVersion: v1
kind: Service
metadata:
  name: host-service
  namespace: mf-workspace
spec:
  type: ClusterIP
  selector:
    app: host
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
