apiVersion: v1
kind: ConfigMap
metadata:
  name: base-nginx-config
  namespace: mf-workspace
data:
  default.conf.template: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }

      location /remoteEntry.js {
        add_header Cache-Control "no-store";
      }

      location / {
        if ($host = "") {
          return 302 http://$host_redirect;
        }
      }
    }
